TMO ™️:
- any: ['**/tmo-fiber/**/*']

Dependencies 📚:
- changed-files:
  - any-glob-to-any-file: ['**/package.json', '**/package-lock.json']

Digicel+ ➕:
- any: ['**/digicel-plus/**/*']

Global 🌐:
- any: ['sites/global/**/*']

Email/PDF template 📄:
- any: ['**/templates/**/*']

Components 📝: 
- any: ['**/components/**/*.vue']

Pages 🖥:
- any: ['**/pages/**/*.vue']

Testing 👨‍💻:
- any: ['**/*.spec.js', '**/*.spec.ts']

INFRA:
  - any: ['**/rs-init.sh']
  - any: ['.github/**']

Documentation:
- changed-files:
  - any-glob-to-any-file: nginx/**