TMO ™️:
- any: ['**/tmo-fiber/**/*']

Dependencies 📚:
- any: ['**/package.json', '**/package-lock.json']

Digicel+ ➕:
- any: ['**/digicel-plus/**/*']

Global 🌐:
- any: ['sites/global/**/*']

Email/PDF template 📄:
- any: ['**/templates/**/*']

Components 📝: 
- any: ['**/components/**/*.vue']

Pages 🖥:
- any: ['**/pages/**/*.vue']

Testing 👨‍💻:
- any: ['**/*.spec.js', '**/*.spec.ts']

INFRA:
  - rs-init.sh