services:
  nextjs-app:
    container_name: nextjs-app
    # command: ["npx prisma generate"]
    # image: csrinu236/medium-nextjs-app # Placeholder for pushing image to Dockerhub
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - nextjs-app-build:/app
      - node_modules:/app/node_modules
      - next:/app/.next
      - prisma:/app/prisma
  nginx:
    container_name: nginx
    # image: csrinu236/medium-nginx-app # Placeholder for pushing image to Dockerhub
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - nextjs-app-build:/app
    depends_on:
      - nextjs-app
    ports:
      - '80:80'

  mongo1:
    container_name: mongo1
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/etc/mongodb/pki/keyfile"]
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ${PWD}/rs_keyfile:/etc/mongodb/pki/keyfile
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
      - ./rs-init.sh:/scripts/rs-init.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    command: ["--replSet", "rs0" ,"--bind_ip_all", "--port", "27018","--keyFile", "/etc/mongodb/pki/keyfile"]
    restart: always
    ports:
      - 27018:27018
    volumes:
      - ${PWD}/rs_keyfile:/etc/mongodb/pki/keyfile
      - "mongo2_data:/data/db"
      - "mongo2_config:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo3:
    image: mongo:7.0
    container_name: mongo3
    command: ["--replSet", "rs0" ,"--bind_ip_all", "--port", "27019","--keyFile", "/etc/mongodb/pki/keyfile"]
    restart: always
    ports:
      - 27019:27019
    volumes:
      - ${PWD}/rs_keyfile:/etc/mongodb/pki/keyfile
      - "mongo3_data:/data/db"
      - "mongo3_config:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  nextjs-app-build: 
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:
  node_modules:
  next:
  prisma: