# apiVersion: v1
# data:
#   password: cGFzc3dvcmQxMjM= //password123
#   username: YWRtaW51c2Vy //adminuser
# kind: Secret
# metadata:
#   name: mongo-creds


apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
type: Opaque
data:
  username: YWRtaW51c2Vy
  password: cGFzc3dvcmQxMjM=