name: Docker build-and-push

on:
  push:
    tags: [ "*" ]
  # pull_request:
  #   branches: [ main ]
    paths:
      - 'frontend/**'
    
env:
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: azure/docker-login@v2
        with:
          login-server: frontend44be2df5.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: frontend44be2df5.azurecr.io/nextjs
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}
          tags: |
            type=edge,branch=$repo.default_branch
            type=semver,pattern=v{{version}}
            type=sha,prefix=,suffix=,format=short

      - name: Create secret file from GitHub Secrets
        run: |
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" > frontend/.env
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" >> frontend/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> frontend/.env

      - name: cat
        run: |
          cat frontend/.env

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: frontend/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # secrets: |
          #   "secret_1=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}"
          #   "secret_2=${{ secrets.CLERK_SECRET_KEY }}"
          #   "secret_3=${{ secrets.DATABASE_URL }}"
          # cache-from: type=gha
          # cache-to: type=gha,mode=max