name: dispatch-trigger-github-releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Create a release from release PRs
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          command: manifest
          config-file: .github/releases/frontend.json
          manifest-file: .github/manifests/frontend.json

      - name: tag major and minor versions
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v4

      - name: tag major and minor versions
        if: ${{ steps.release.outputs.releases_created }}
        env:
          pkg: frontend
        run: |
          git config user.name release
          git config user.email release@release-bot.com
          git remote add gh-token "https://${{ secrets.MY_RELEASE_PLEASE_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d ${pkg}-v${{ steps.release.outputs['frontend--major'] }} || true
          git tag -d ${pkg}-v${{ steps.release.outputs['frontend--major'] }}.${{ steps.release.outputs['frontend--minor'] }} || true
          git push origin :${pkg}-v${{ steps.release.outputs['frontend--major'] }} || true
          git push origin :${pkg}-v${{ steps.release.outputs['frontend--major'] }}.${{ steps.release.outputs['frontend--minor'] }} || true
          git tag -a ${pkg}-v${{ steps.release.outputs['frontend--major'] }} -m "Release v${{ steps.release.outputs['frontend--major'] }}"
          git tag -a ${pkg}-v${{ steps.release.outputs['frontend--major'] }}.${{ steps.release.outputs['frontend--minor'] }} -m "Release v${{ steps.release.outputs['frontend--major'] }}.${{ steps.release.outputs['frontend--minor'] }}"
          git push origin ${pkg}-v${{ steps.release.outputs['frontend--major'] }}
          git push origin ${pkg}-v${{ steps.release.outputs['frontend--major'] }}.${{ steps.release.outputs['frontend--minor'] }}
