name: dispatch-trigger-github-releases


permissions:
  contents: write
  pull-requests: write
  repository-projects: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Create a release from release PRs
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          config-file: .github/releases/frontend.json
          manifest-file: .github/manifests/frontend.json

      - name: actions/checkout
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v4

      - name: tag major and minor versions
        if: ${{ steps.release.outputs.releases_created }}
        env:
          pkg: frontend
        run: |
          set -e
          git config user.name "release"
          git config user.email "release@release-bot.com"
          git remote add gh-token "https://${{ secrets.MY_RELEASE_PLEASE_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          
          major_version=${{ steps.release.outputs['frontend--major'] }}
          minor_version=${{ steps.release.outputs['frontend--minor'] }}

          # Check if major_version and minor_version are set
          if [ -z "$major_version" ]; then
            echo "Major version is not set. Exiting."
            exit 1
          fi
          if [ -z "$minor_version" ]; then
            echo "Minor version is not set. Exiting."
            exit 1
          fi

          major_tag="${pkg}-v${major_version}"
          minor_tag="${pkg}-v${major_version}.${minor_version}"

          # Delete existing tags if they exist
          git tag -d $major_tag 2>/dev/null || true
          git tag -d $minor_tag 2>/dev/null || true
          git push origin :$major_tag 2>/dev/null || true
          git push origin :$minor_tag 2>/dev/null || true

          # Create and push new tags
          git tag -a $major_tag -m "Release v${major_version}"
          git tag -a $minor_tag -m "Release v${major_version}.${minor_version}"
          git push origin $major_tag
          git push origin $minor_tag