name: dispatch-trigger-github-releases


permissions:
  contents: write
  pull-requests: write
  repository-projects: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Create a release from release PRs
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          config-file: .github/releases/frontend.json
          manifest-file: .github/manifests/frontend.json

      - name: git
        # if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v4

      - name: tag major and minor versions
        if: ${{ steps.release.outputs.releases_created }}
        env:
          pkg: frontend
        run: |
          git config user.name "release"
          git config user.email "release@release-bot.com"
          
          # Delete existing tags if they exist
          git tag -d ${pkg}-v${{ steps.release.outputs['frontend--major'] }} 2>/dev/null || true
          git tag -d ${pkg}-v${{ steps.release.outputs['frontend--major'] }}.${{ steps.release.outputs['frontend--minor'] }} 2>/dev/null || true
          git push origin :${pkg}-v${{ steps.release.outputs['frontend--major'] }} 2>/dev/null || true
          git push origin :${pkg}-v${{ steps.release.outputs['frontend--major'] }}.${{ steps.release.outputs['frontend--minor'] }} 2>/dev/null || true
          
          # Create new tags
          git tag -a ${pkg}-v${{ steps.release.outputs['frontend--major'] }} -m "Release v${{ steps.release.outputs['frontend--major'] }}"
          git tag -a ${pkg}-v${{ steps.release.outputs['frontend--major'] }}.${{ steps.release.outputs['frontend--minor'] }} -m "Release v${{ steps.release.outputs['frontend--major'] }}.${{ steps.release.outputs['frontend--minor'] }}"
          
          # Push new tags
          git push origin ${pkg}-v${{ steps.release.outputs['frontend--major'] }}
          git push origin ${pkg}-v${{ steps.release.outputs['frontend--major'] }}.${{ steps.release.outputs['frontend--minor'] }}