name: dispatch-trigger-github-releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create a release from release PRs
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          command: manifest
          config-file: .github/releases/frontend.json
          manifest-file: .github/manifests/frontend.json