name: az-oidc-test

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write
  statuses: write


# subject on oidc : pullrequest or environment:
# if environment specified on job (pull request) does not work
jobs:
  plan-rg:
    runs-on: ubuntu-latest
    name: plan rg
    # environment:
    #   name: dev
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ARM_SKIP_PROVIDER_REGISTRATION: true
      CONFIG_DIRECTORY: project
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: debug
        run: |
          echo "$GITHUB_CONTEXT"
          env
          echo ${ACTIONS_ID_TOKEN_REQUEST_URL}
          echo ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}
      # Install the latest version of the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init
        with:
          directory: ${{ env.CONFIG_DIRECTORY }}

